version: '3.1'

services:

  mysql:
    image: mysql:8.0.16
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://192.168.1.2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1
  
  dbz:
    image: debezium/connect:1.1.0.Final
    hostname: dbz
    ports:
     - 8083:8083
    environment:
     - BOOTSTRAP_SERVERS=kafka1:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=dbz_config_1
     - OFFSET_STORAGE_TOPIC=dbz_offsets_1
     - STATUS_STORAGE_TOPIC=dbz_status_1
     - JAVA_OPTS='-Xmx1G'
    restart: always
    depends_on:
      - kafka1
    links:
      - kafka1
      - zoo1